version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "dependencies"
    groups:
      go.opentelemetry.io:
        patterns:
          - "go.opentelemetry.io/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
